# Generated by Django 5.1.8 on 2025-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=400)),
                ('htmlCss', models.IntegerField()),
                ('js', models.IntegerField()),
                ('react', models.IntegerField()),
                ('dj', models.IntegerField()),
                ('sql', models.IntegerField()),
            ],
        ),
    ]
