# Generated by Django 5.1.8 on 2025-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='desc2',
            field=models.CharField(default='random', max_length=400),
            preserve_default=False,
        ),
    ]
