# Generated by Django 5.1.8 on 2025-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_contact_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='desc',
            new_name='long_desc',
        ),
        migrations.AddField(
            model_name='projects',
            name='short_desc',
            field=models.CharField(default='Long desc', max_length=400),
            preserve_default=False,
        ),
    ]
