# Generated by Django 5.1.8 on 2025-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_desc_projects_long_desc_projects_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='gitLink',
            field=models.URLField(default='https://www.github.com', max_length=100),
            preserve_default=False,
        ),
    ]
